/**
 * Fallback-skill synthesizer.
 *
 * When an A2A agent's card advertises zero skills, the bridge would otherwise
 * project zero tools from it — giving an MCP client no way to interact with
 * that agent at all. We synthesize a single "message" skill whose input
 * schema accepts a free-form `message: string` and whose description carries
 * the agent's identity, so even if the tool is never invoked, the client
 * (including an LLM) can see which agent it belongs to.
 *
 * The synthetic skill is tagged with `FALLBACK_SKILL_TAG`; the invocation
 * runtime checks this tag to dispatch a plain text A2A message instead of
 * the usual `{skillId, args}` data part.
 *
 * Pure function — same input ⇒ same output.
 *
 * @module core/fallback-skill
 */

import type { ResolvedAgent, ResolvedSkill } from '../types/index.js';

export type FallbackMode = 'none' | 'message';

/** Reserved tag that marks a skill as the bridge-generated fallback. */
export const FALLBACK_SKILL_TAG = '__bridge-fallback__';

/** Reserved skill id for the fallback (also the tool-name suffix). */
export const FALLBACK_SKILL_ID = 'message';

/**
 * Return a new ResolvedAgent with a fallback skill appended when the agent
 * has zero skills and mode is `'message'`. Otherwise returns the input
 * unchanged.
 */
export function applyFallbackSkill(
  agent: ResolvedAgent,
  mode: FallbackMode,
): ResolvedAgent {
  if (mode === 'none') return agent;
  if (agent.skills.length > 0) return agent;

  const identity =
    agent.description && agent.description.trim().length > 0
      ? `${agent.name} — ${agent.description}`
      : agent.name;

  const synthetic: ResolvedSkill = {
    id: FALLBACK_SKILL_ID,
    name: 'Send message',
    description: `${identity}. This agent advertises no skills; send it a free-form message.`,
    tags: [FALLBACK_SKILL_TAG],
    inputSchema: {
      type: 'object',
      properties: {
        message: {
          type: 'string',
        },
      },
      required: ['message'],
    },
    inputModes: ['text'],
    outputModes: ['text'],
    agentUrl: agent.url,
    agentId: agent.id,
  };

  return { ...agent, skills: [synthetic] };
}

/** True if the skill was generated by `applyFallbackSkill`. */
export function isFallbackSkill(skill: ResolvedSkill): boolean {
  return skill.tags.includes(FALLBACK_SKILL_TAG);
}
